version: "3"

services:

  node:
    image: alissondocker31/node
    container_name: express
    build:
      context: ./
    restart: always
    networks:
      - nodenet

  nginx:
    image: alissondocker31/nginx
    container_name: nginx
    build:
      context: ./nginx  
    networks:
      - nodenet
    ports:
      - "8080:80"
   
   db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nodenet


networks:
  nodenet:
    driver: bridge            
