version: "3"

services:

  node:
    image: alissondocker31/node
    container_name: express
    build:
      context: ./node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh  
    volumes:
      - ./node/src:/home/node/projeto/src 
    command: npm run dev  
    restart: always
    depends_on:
      - db
    networks:
      - nodenet

  nginx:
    image: alissondocker31/nginx
    container_name: nginx
    build:
      context: ./nginx  
    networks:
      - nodenet
    depends_on:
      - node  
    ports:
      - "8080:80"
   
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0 --init-file /docker-entrypoint-initdb.d/init-script.sql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nodenet


networks:
  nodenet:
    driver: bridge            
